# Generated by Django 5.2.8 on 2026-03-16 19:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_envio', models.DateTimeField(auto_now_add=True)),
                ('tipo_atendimento', models.CharField(choices=[('EMISSAO', 'Emissão'), ('SERVICO', 'Serviço'), ('INFORMACAO', 'Informação')], max_length=20)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome_completo', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=150, null=True)),
                ('nivel_acesso', models.CharField(choices=[('ATENDENTE', 'Atendente'), ('ATENDENTE_II', 'Atendente II'), ('SUPERVISOR', 'Supervisor'), ('GERENTE', 'Gerente')], default='ATENDENTE', max_length=20)),
                ('primeiro_acesso', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_posto', models.CharField(max_length=100)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postos_criados', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postos_gerenciados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEmissao',
            fields=[
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registros.registro')),
                ('nome', models.CharField(max_length=150)),
                ('tipo_cartao', models.CharField(choices=[('VALE TRANSPORTE', 'Vale Transporte'), ('COMUM', 'Comum'), ('ESCOLAR', 'Escolar'), ('ESC GRATUIDADE', 'Escolar Gratuidade'), ('PCD', 'PCD'), ('FUNC SISTEMA', 'Func. Sistema'), ('IMMU', 'IMMU'), ('FUNCIONAL', 'Funcional'), ('IDOSO', 'Idoso'), ('SINETRAM', 'Sinetram'), ('P SOCIAL', 'P. Social')], max_length=30)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroInformacao',
            fields=[
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registros.registro')),
                ('informacao_passada', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroServico',
            fields=[
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registros.registro')),
                ('servico_realizado', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='atendente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registro',
            name='posto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.posto'),
        ),
        migrations.CreateModel(
            name='RegistroAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_tentado', models.CharField(max_length=50)),
                ('ip_maquina', models.GenericIPAddressField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('status_sucesso', models.BooleanField(default=False)),
                ('mensagem_falha', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoLotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('status_lotacao', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('alocado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_lotacao', to=settings.AUTH_USER_MODEL)),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.posto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status_lotacao', 'A')), fields=('usuario',), name='unique_active_lotacao_per_user')],
            },
        ),
    ]
