# Generated by Django 5.2.8 on 2025-11-13 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_envio', models.DateTimeField(auto_now_add=True)),
                ('login_atendente', models.CharField(max_length=50)),
                ('id_local_posto', models.IntegerField()),
                ('tipo_atendimento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TiposCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iss_id', models.CharField(max_length=2)),
                ('cd_id', models.CharField(max_length=2)),
                ('prefixo', models.CharField(max_length=5, unique=True)),
                ('nome_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroBiometria',
            fields=[
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registros.registro')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo_cartao', models.CharField(max_length=50)),
                ('tipo_biometria', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=11)),
                ('numero_cartao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEmissao',
            fields=[
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registros.registro')),
                ('numero_cartao', models.CharField(max_length=20)),
                ('tipo_cartao', models.CharField(max_length=50)),
                ('via_cartao', models.CharField(default='1ª VIA', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroInformacao',
            fields=[
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registros.registro')),
                ('tipo_informacao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroServico',
            fields=[
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registros.registro')),
                ('tipo_servico', models.CharField(max_length=50)),
            ],
        ),
    ]
