# Generated by Django 5.2.8 on 2026-03-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroemissao',
            name='cartao_impresso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroemissao',
            name='via',
            field=models.CharField(blank=True, choices=[('1ª', '1ª Via'), ('2ª', '2ª Via'), ('3ª+', '3ª Via ou mais')], default='1ª', max_length=10, null=True),
        ),
    ]
