# Generated by Django 5.2.8 on 2026-03-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_registroemissao_cartao_impresso_registroemissao_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroemissao',
            name='cartao_impresso',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
