# Generated by Django 5.2.8 on 2026-03-17 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_registroemissao_cartao_impresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='posto',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='posto',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postos_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posto',
            name='tipo',
            field=models.CharField(choices=[('FIXO', 'Fixo'), ('ITINERANTE', 'Itinerante'), ('VIRTUAL', 'Virtual')], default='FIXO', max_length=20),
        ),
    ]
