# Generated by Django 5.2.8 on 2026-03-18 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_posto_atualizado_em_posto_atualizado_por_posto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/'),
        ),
        migrations.CreateModel(
            name='LogAlteracaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('quem_alterou', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_gerados', to=settings.AUTH_USER_MODEL)),
                ('usuario_afetado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_sofridos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
